---
title: "workout01-viren-gupta"
author: "Viren Gupta"
date: "3/11/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 5.1) Effective Shooting Percentage

```{r shots}
total <- read.csv("../data/shots-data.csv")
iggy <- read.csv("../data/andre-iguodala.csv")
steph <- read.csv("../data/stephen-curry.csv")
dray <- read.csv("../data/draymond-green.csv")
kev <- read.csv("../data/kevin-durant.csv")
klay <- read.csv("../data/klay-thompson.csv")
table1 <- iggy[iggy$shot_type == "2PT Field Goal",]
y <- table1[table1$shot_made_flag == 'y',]
iggydata2 <- c('Andre Iguodala', nrow(table1), nrow(y), nrow(y)/ nrow(table1) * 100)
table2 <- dray[dray$shot_type == "2PT Field Goal",]
x <- table2[table2$shot_made_flag == 'y',]
draydata2 <- c('Draymond Green', nrow(table2), nrow(x), nrow(x)/ nrow(table2) * 100)
table3 <- kev[kev$shot_type == "2PT Field Goal",]
z <- table3[table3$shot_made_flag == 'y',]
kevdata2 <- c('Kevin Durant', nrow(table3), nrow(z), nrow(z)/ nrow(table3) * 100)
table4 <- klay[klay$shot_type == "2PT Field Goal",]
a <- table4[table4$shot_made_flag == 'y',]
klaydata2 <- c('Klay Thompson', nrow(table4), nrow(a), nrow(a)/ nrow(table4) * 100)
table5 <- steph[steph$shot_type == "2PT Field Goal",]
b <- table5[table5$shot_made_flag == 'y',]
stephdata2 <- c('Stephen Curry', nrow(table5), nrow(b), nrow(b)/ nrow(table5) * 100)
esp2 <- rbind(iggydata2, draydata2, kevdata2, klaydata2, stephdata2)
esp2
table6 <- steph[steph$shot_type == "3PT Field Goal",]
c <- table5[table5$shot_made_flag == 'y',]
stephdata3 <- c('Stephen Curry', nrow(table6), nrow(c), nrow(c)/ nrow(table6) * 100)
table7 <- klay[klay$shot_type == "3PT Field Goal",]
d <- table7[table7$shot_made_flag == 'y',]
klaydata3 <- c('Klay Thompson', nrow(table7), nrow(d), nrow(d)/ nrow(table7) * 100)
table8 <- kev[kev$shot_type == "3PT Field Goal",]
e <- table8[table8$shot_made_flag == 'y',]
kevdata3 <- c('Kevin Durant', nrow(table8), nrow(e), nrow(e)/ nrow(table8) * 100)
table9 <- dray[dray$shot_type == "3PT Field Goal",]
f <- table9[table9$shot_made_flag == 'y',]
draydata3 <- c('Draymond Green', nrow(table9), nrow(f), nrow(f)/ nrow(table9) * 100)
table10 <- iggy[iggy$shot_type == "3PT Field Goal",]
g <- table10[table10$shot_made_flag == 'y',]
iggydata3 <- c('Andre Iguodala', nrow(table10), nrow(g), nrow(g)/ nrow(table10) * 100)
esp3 <- rbind(iggydata3, draydata3, kevdata3, klaydata3, stephdata3)
esp3
iggydatasum <- c('Andre Iguodala', nrow(iggy), 58 + 134,  (58 + 134) / nrow(iggy) * 100)
draydatasum <- c('Draymond Green', nrow(dray), 171 + 74,  (171 + 74) / nrow(dray) * 100)
kevdatasum <- c('Kevin Durant', nrow(kev), 390 + 105,  (390 + 105) / nrow(kev) * 100)
klaydatasum <- c('Klay Thompson', nrow(klay), 329 + 246,  (329 + 246) / nrow(klay) * 100)
stephdatasum <- c('Stephen Curry', nrow(steph), 304 + 304,  (304 + 304) / nrow(steph) * 100)
espsum <- rbind(iggydatasum, draydatasum, kevdatasum, klaydatasum, stephdatasum)
espsum
```

## 5.2 Narrative


